server:
  port: 8090
  servlet:
    context-path: /
    session:
      timeout: 600s
  error:
    include-message: always

spring:
  application:
    name: vpn-manager
  datasource:
    url: ${YDB_URL}
    driver-class-name: tech.ydb.jdbc.YdbDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ru.itmo.vpnapp.hibernate.YDBDialect
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      
tg:
  bot:
    token: ${TG_BOT_TOKEN}
    username: ${TG_BOT_USERNAME}
    creatorId: ${TG_BOT_CREATOR_ID}
    
ssh:
  scripts:
    add_client: 
      path: ${SSH_ADD_CLIENT_SCRIPT}